------------------------- Create DMR database -------------------------
USE [master]
GO

/****** Object:  Database [DMR]    Script Date: 4/18/2020 12:15:25 ******/
CREATE DATABASE [DMR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DMR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DMR.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DMR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DMR_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DMR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DMR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DMR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DMR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DMR] SET ARITHABORT OFF 
GO

ALTER DATABASE [DMR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DMR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DMR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DMR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DMR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DMR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DMR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DMR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DMR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DMR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DMR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DMR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DMR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DMR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DMR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DMR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DMR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DMR] SET RECOVERY FULL 
GO

ALTER DATABASE [DMR] SET  MULTI_USER 
GO

ALTER DATABASE [DMR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DMR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DMR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DMR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DMR] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DMR] SET QUERY_STORE = OFF
GO

USE [DMR]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DMR] SET  READ_WRITE 
GO


------------------------- Create DMR id user table -------------------------

USE [DMR]
GO

/****** Object:  Table [dbo].[user]    Script Date: 4/18/2020 12:16:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[user](
	[RADIO_ID] [varchar](50) NOT NULL,
	[CALLSIGN] [varchar](255) NULL,
	[FIRST_NAME] [varchar](255) NULL,
	[LAST_NAME] [varchar](255) NULL,
	[CITY] [varchar](255) NULL,
	[STATE] [varchar](255) NULL,
	[COUNTRY] [varchar](255) NULL,
	[REMARKS] [varchar](255) NULL,
 CONSTRAINT [PK_user] PRIMARY KEY CLUSTERED 
(
	[RADIO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


------------------------- Create ProScan View -------------------------

USE [DMR]
GO

/****** Object:  View [dbo].[proscan]    Script Date: 4/18/2020 12:16:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE view [dbo].[proscan] as 
SELECT REPLACE(rtrim(CONCAT(REPLACE([RADIO_ID], ' ', '')
	  , ' LOGTEXT='
      ,REPLACE([CALLSIGN], ' ', '')
	  ,' '
      ,REPLACE([FIRST_NAME], ' ', '')
	  ,' '
      ,REPLACE([LAST_NAME], ' ', '')
	  ,' '
	  ,REPLACE([STATE], ' ', ''))), '  ', ' ') AS [#SQL]
  FROM [dbo].[user]
  where len([RADIO_ID]) > 0

GO


------------------------- Create Anytone View -------------------------

USE [DMR]
GO

/****** Object:  View [dbo].[anytone]    Script Date: 4/18/2020 12:17:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/****** Script for SelectTopNRows command from SSMS  ******/
CREATE view [dbo].[anytone] as

SELECT '' AS [No.]	  
	  ,[RADIO_ID] AS [Radio ID]
      ,[CALLSIGN] AS [Callsign]
      ,CONCAT([FIRST_NAME], ' ', [LAST_NAME]) AS [Name]
      ,[CITY] AS [City]
      ,[STATE] AS [State]
      ,[COUNTRY] AS [Country]
      ,'' AS [Remarks]
	  ,'' AS [Call Type]
	  ,'' AS [Call Alert]
  FROM [DMR].[dbo].[user]

GO
